#!/usr/bin/python3


def raise_exception():

    error = []

    print("{:d}".format(error))
